### ISSUE TITLE
Inconsistent cursor size

### ISSUE THREAD

**Issue by marlock9** [decathorpe/pantheon-session-settings#5]
Hello!
By default after installation I have rather big (for my taste, 48px) cursor size in almost all desktop: LightDM, Desktop, wingpanel, plank, window decorations.
But inside the application windows I have (suddenly!) 24px cursor. Moreover, on screenshots it is not noticeable!
![Screenshot from 2019-06-24 08 52 22](https://user-images.githubusercontent.com/9781492/59994775-c8699b80-965d-11e9-80ad-cfb983bdff4e.png)
![Screenshot from 2019-06-24 08 52 28](https://user-images.githubusercontent.com/9781492/59994776-cacbf580-965d-11e9-81cc-f00e1bfe924f.png)
On the last screenshot cursor is 24px, but in fact it's 48px.

**Comment by decathorpe** [comment]
By "not noticable on screenshots", you mean that the screenshots do not reflect the actual contents of the screen?

Are you using a HiDPI screen with 2x window scaling active?

**Comment by marlock9** [comment]
> By "not noticable on screenshots", you mean that the screenshots do not reflect the actual contents of the screen?
Yes, exactly.
> I use 32 inch 2K display, so it isn't HiDPI, just 96 DPI.

**Comment by decathorpe** [comment]
That's interesting.

Which applications are affected by this?
Is it dependent on the icon theme?

**Comment by decathorpe** [comment]
Ah, I think I know the issue. It used to happen to me too, with older versions of gnome-shell. Sometimes the cursor size would change when hovering over other windows.

Which version of fedora are you using?

**Comment by marlock9** [comment]
Fedora 30.

**Comment by decathorpe** [comment]
Can you try running:

`gsettings set org.gnome.desktop.interface cursor-size 24`

**Comment by marlock9** [comment]
Tried to do it through dconf-editor (both as user and as root) - nothing changed.
Also now I have gtk-cursor-theme-size = 24 in /etc/gtk-3.0/settings.ini but this also does not affect.

**Comment by decathorpe** [comment]
I'm not at my PC right now, but can you check if there's a corresponding cursor-size setting in gala?

(Also, please don't do such things as root. It can seriously mess up your system.)

**Comment by marlock9** [comment]
>if there's a corresponding cursor-size setting in gala?

Didn't find through dconf-editor's search.

**Comment by decathorpe** [comment]
Alright, I can confirm some kind of weird issue in my test VM - the size of the cursor definitely changes when hovering windows. I'll ask gala upstream about this.

**Comment by decathorpe** [comment]
Upon further investigation, it looks like this is a known upstream issue and unrelated to fedora:

https://github.com/elementary/gala/issues/300
https://github.com/elementary/switchboard-plug-display/issues/141

So there's not really anything I can do about this at the packaging level, sorry.
Maybe you can chime in on the issues I linked above, if they ask for help with testing or debugging.

**Comment by marlock9** [comment]
I have workaround!
Just enabled autologin for my user in /etc/lightdm/lightdm.conf and my cursor now 24px all around the desktop!
It is probably bug in io.elementary.greeter.

**Comment by decathorpe** [comment]
Yeah, it's probably a bug in either of these components ...
